### ISSUE TITLE
Interface: Fragen anlegen

### ISSUE THREAD

**Issue by danmcatee** [OpenTechSchool-Leipzig/poll_app#3]
Editor View um Fragen anzulegen

**Comment by danmcatee** [comment]
{
    "text": "",
    "type": [""],
    "answers?": [""]
}

**Comment by danmcatee** [comment]
[Fragebogen](https://start-coding-now.slack.com/messages/DJENS8PV5/convo/GED0T2AR3-1556816907.007900/)

**Comment by markusphil** [comment]
Ich hab mir heute nochmal Gedanken zu den question types gemacht.

**Comment by markusphil** [comment]
Ich hab jetzt mal ein einfaches Formular gebaut, dass die verschiedenen Optionen abdeckt. Ich hab aber einen sehr komischen bug verursacht. Die objects im parent array bleiben mit dem child component verbunden und werden also immer überschrieben - das verstehe ich nicht so ganz! :D
