### ISSUE TITLE
Interface: Workshop anlegen

### ISSUE THREAD

**Issue by danmcatee** [OpenTechSchool-Leipzig/poll_app#4]
- Titel angeben
- Fragen auswählen
- Fragen erstellen 
- Datum angeben (Moment.js)
- (Template speichern)

**Comment by danmcatee** [comment]
{
    "title": "",
    "date": "",
    "questions": [""]
}

**Comment by markusphil** [comment]
Konzept: https://www.figma.com/file/aCBW5nnBFWYDpPrmh1oUf6Kb/Poll_App?node-id=0%3A1
