### ISSUE TITLE
Interface: Admin Dashboard

### ISSUE THREAD

**Issue by danmcatee** [OpenTechSchool-Leipzig/poll_app#5]
- Workshop anlegen
- Liste aller Workshops
- Auswertung

**Comment by markusphil** [comment]
Hey @AlexanderBoenninger tatsächlich funktioniert es genauso, wie du es skizziert hast. Die Fragen lassen sich zu Fragebögen zusammenstellen (Polls) oder als Template speichern. Diese Templates lassen sich laden und modifizieren und können dann als a) als neue Poll oder b) als neues Template oder c) als Änderung am ausgewählten Template gespeichert werden

Aber du hast recht: die Benennungen sind sehr verwirrend! Siehe auch #38

**Comment by AlexanderBoenninger** [comment]
Ok. Gut wenn es auch Polls als Sammlung von Fragen / Tamplates gibt.
Bin mir aber nicht sicher ob es richtig rüber gekommen ist.
Beispiel: Es gibt eine Umfrage in der man Persönliche Daten erheben will und dann Fragen zu dem Thema Urlaubsvorlieben stellt. Anschließden wird man noch gefragt, wie man persönlich versucht ölologisch und nachhaltig zu leben.

Die Fragen könnte man super in 3 Tamplates zusammenfassen, weil man sie wohlmöglich öffters nutzen möchte. 1.Persönliches, 2. Urlaubsvorlieben 3. Ökologischesleben

Diese Tamplates würd ich dann in einer Poll zusammen setzen können.
Es würde keinen Sinn ergeben ein Tamplate als Poll zu speichern, weil das Tamplate ein Baustein des Polls ist. 
Wenn das/der/die Poll nur ein Tamplate hat, hat es halt ein Tamplete – wird dann aber nicht zum Poll.

Sollte man keine Tamplates haben wollen, sollte man wie jetzt auch schon der Fall auch einfach nur Fragen in die Poll Laden können. 

Ich würde nicht empfehlen Die Elemente in einander umwandelbar zu machen. 
Die Einfachheit hier gewinnen.
Vielleicht kann man Tamplates "auflösen", die Fragen bleiben dann aber an der Stelle in der Poll vorhanden. (Das würde sich verhalten wie Gruppieren und Entgruppieren in den meisten Grafik Programmen)

Naming Problem hab ich angeschaut und überlege mir da auch noch was.

**Comment by markusphil** [comment]
Jetzt hab ich verstanden, was du meinst! Nein die Templates sind keine weiteren Bausteine, sondern die Vorlage für eine komplette Umfrage mit der gleichen Datenstruktur.

Der Gedanke dahinter ist, relativ spezifisch an die Evaluation von Veranstaltungen ausgerichtet. Sodass man für die Umfragen dann die Templates als Basis nimmt und nur noch die Details für die jeweilige Veranstaltung anpassen muss. Ist das verständlich?

**Comment by AlexanderBoenninger** [comment]
Verstanden, aber wiedersprechen würde sich das was du sagst mit meiner "Vision" oder Verständniss der App ja nicht. 
Man könnte ja auch nur ein Tamplate in die Umfrage laden. Jeweils das Tamplate, das gerade für die Veranstatlungsform passt. Oder man kann mehrere Tamplates laden um sie wie Bausteine zu benutzen, die es ermöglichen die Umfragen freier und effizienter durchzuführen.

**Comment by markusphil** [comment]
Stimmt, und ich finde deine Idee auch gut. Die können wir gerne im Hinterkopf behalten. Ich würde aber gerne erstmal versuchen, die vorhandenen Funktionen auszuarbeiten und zu verbessern.

Momentan ist der einzige Unterschied zwischen Templates und Polls, dass erstere modifzierbar sind, wohingegen eine einmal erstell Poll nicht mehr geändert werden kann. Das ist wichtig für die Auswertung.

**Comment by AlexanderBoenninger** [comment]
ok. So machen wir es
