### ISSUE TITLE
Disallow poll dates in the past on poll creation

### ISSUE THREAD

**Issue by dkellner** [OpenTechSchool-Leipzig/poll_app#54]
We could validate the date on "Create Poll" and at least warn about creating a poll with a date in the past. I think this would be a good first issue for new contributors, too.

**Comment by markusphil** [comment]
Thanks to @ratracegrad for your contribution! 😊 Now the user cannot input a date that lies in the past.  There is however one problem left.Tthe validation checks aplies on every input. So when you start typing a date the error will be shown and you cannot continue inputing your date.

And actually I think it is a not that unusal case that someone needs to create a evaluation survey for an event that lies in the pass. So maybe we should just show a warning, without clearing the input. What do you think?
